apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: 10.141.212.25:5555/cluster-ts-redis
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-account-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-account-mongo
    spec:
      containers:
      - name: ts-account-mongo
        image: 10.141.212.25:5555/cluster-ts-mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-route-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-route-mongo
    spec:
      containers:
      - name: ts-route-mongo
        image: 10.141.212.25:5555/cluster-ts-mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-contacts-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-contacts-mongo
    spec:
      containers:
      - name: ts-contacts-mongo
        image: 10.141.212.25:5555/cluster-ts-mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-order-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-order-mongo
    spec:
      containers:
      - name: ts-order-mongo
        image: 10.141.212.25:5555/cluster-ts-mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-order-other-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-order-other-mongo
    spec:
      containers:
      - name: ts-order-other-mongo
        image: 10.141.212.25:5555/cluster-ts-mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-config-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-config-mongo
    spec:
      containers:
      - name: ts-config-mongo
        image: 10.141.212.25:5555/cluster-ts-mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-station-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-station-mongo
    spec:
      containers:
      - name: ts-station-mongo
        image: 10.141.212.25:5555/cluster-ts-mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-train-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-train-mongo
    spec:
      containers:
      - name: ts-train-mongo
        image: 10.141.212.25:5555/cluster-ts-mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-travel-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-travel-mongo
    spec:
      containers:
      - name: ts-travel-mongo
        image: 10.141.212.25:5555/cluster-ts-mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-travel2-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-travel2-mongo
    spec:
      containers:
      - name: ts-travel2-mongo
        image: 10.141.212.25:5555/cluster-ts-mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-price-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-price-mongo
    spec:
      containers:
      - name: ts-price-mongo
        image: 10.141.212.25:5555/cluster-ts-mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-security-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-security-mongo
    spec:
      containers:
      - name: ts-security-mongo
        image: 10.141.212.25:5555/cluster-ts-mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-inside-payment-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-inside-payment-mongo
    spec:
      containers:
      - name: ts-inside-payment-mongo
        image: 10.141.212.25:5555/cluster-ts-mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-payment-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-payment-mongo
    spec:
      containers:
      - name: ts-payment-mongo
        image: 10.141.212.25:5555/cluster-ts-mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-assurance-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-assurance-mongo
    spec:
      containers:
      - name: ts-assurance-mongo
        image: 10.141.212.25:5555/cluster-ts-mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-ticket-office-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-ticket-office-mongo
    spec:
      containers:
      - name: ts-ticket-office-mongo
        image: 10.141.212.25:5555/cluster-ts-mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-food-map-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-food-map-mongo
    spec:
      containers:
      - name: ts-food-map-mongo
        image: 10.141.212.25:5555/cluster-ts-mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-consign-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-consign-mongo
    spec:
      containers:
      - name: ts-consign-mongo
        image: 10.141.212.25:5555/cluster-ts-mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-consign-price-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-consign-price-mongo
    spec:
      containers:
      - name: ts-consign-price-mongo
        image: 10.141.212.25:5555/cluster-ts-mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ts-food-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ts-food-mongo
    spec:
      containers:
      - name: ts-food-mongo
        image: 10.141.212.25:5555/cluster-ts-mongo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017